# Основные метаданные проекта
sonar.projectKey=SeaBattle
sonar.projectName=SeaBattle
sonar.projectVersion=1.0

# Пути к исходному коду (анализируем только папку Source)
sonar.sources=Source
# Исключаем автосгенерированный код Unreal Engine, чтобы не тратить лимиты строк (LOC)
sonar.exclusions=Source/**/*.generated.h, Source/ThirdParty/**

# Путь к сгенерированной базе данных компиляции
sonar.cfamily.compile-commands=compile_commands.json

# Кодировка файлов
sonar.sourceEncoding=UTF-8